baseURL = "https://shaharnaveh.github.io"
defaultContentLanguage = "en"
title = "Mediocre Blog"

enableRobotsTXT = true 

enableGitInfo = false # whether to use git commit log
enableEmoji = true 

theme = "DoIt"
