baseURL: https://shaharnaveh.github.io/
title: Shahar Naveh
theme: hextra

enableRobotsTXT: true
enableGitInfo: true
enableEmoji: true
hasCJKLanguage: false
enableInlineShortcodes: true
summaryLength: 0

defaultContentLanguage: en 
languageCode: en-us 
languages:
  en:
    languageCode: en-US
    languageName: English
    weight: 1
    title: Shahar Naveh
