baseURL: https://shaharnaveh.github.io/
title: Shahar Naveh
theme: hextra

enableRobotsTXT: true
enableGitInfo: true
enableEmoji: true
hasCJKLanguage: false
enableInlineShortcodes: true
summaryLength: 0

defaultContentLanguage: en 
languageCode: en-us 
languages:
  en:
    languageCode: en-US
    languageName: English
    weight: 1
    title: Shahar Naveh

module:
  hugoVersion:
    extended: true
    min: "0.112.0"
   
outputs:
  home:
    - HTML 
    - RSS 
    - JsonFeed
  page:
    - HTML 
  section:
    - HTML 
    - RSS
    
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
  tableOfContents:
    startLevel: 2
    endLevel: 4

menu:
  main:
    - identifier: blog
      name: Blog
      pageRef: /blog
      weight: 1
    - name: GitHub
      weight: 2
      url: "https://github.com/ShaharNaveh/"
      params:
        icon: github
    - name: Search
      weight: 3
      params:
        type: search
