goldmark:
  renderer:
    unsafe: true
  parser:
    attribute:
      block: true
    
highlight:
  noClasses: false
  codeFences: true
  anchorLineNos: true
  
tableOfContents:
  startLevel: 2
  endLevel: 4
