[languages]
  [languages.en]
    weight = 1
    title = "Mediocre Blog"
    languageCode = "en"
    languageName = "English"
    [[languages.en.menu.main]]
      identifier = "posts"
      #pre = ""
      #post = ""
      name = "Posts"
      url = "/posts/"
      title = "Mediocre Posts"
      weight = 1
    [[languages.en.menu.main]]
      identifier = "tags"
      #pre = ""
      #post = ""
      name = "Tags"
      url = "/tags/"
      title = "Mediocre Tags"
      weight = 2
    [[languages.en.menu.main]]
      identifier = "categories"
      #pre = ""
      #post = ""
      name = "Categories"
      url = "/categories/"
      title = "Mediocre Categories"
      weight = 3
