description: Explore unconventional applications of technology to broaden your perspectives and enhance efficiency
displayUpdatedDate: false
dateFormat: January 2, 2006

navbar:
  displayTitle: true
  displayLogo: false
  logo:
    path: images/logo.svg
    dark: images/logo.svg # images/logo-dark.svg
    # width: 40
    # height: 20
    link: /
  width: wide

page:
  # full (100%), wide (90rem), normal (1280px)
  width: normal
  tabs:
    sync: true

theme:
  # light | dark | system
  default: system
  displayToggle: true

footer:
  enable: true
  displayCopyright: true
  displayPoweredBy: false
  width: normal
  
# Search
# flexsearch is enabled by default
search:
  enable: true
  type: flexsearch

  flexsearch:
    # index page by: content | summary | heading | title
    index: content
    # full | forward | reverse | strict
    # https://github.com/nextapps-de/flexsearch/#tokenizer-prefix-search
    tokenize: forward

editURL:
  enable: true
  base: https://github.com/ShaharNaveh/ShaharNaveh.github.io/edit/main/content

blog:
  list:
    displayTags: true
    # date | lastmod | publishDate | title | weight
    sortBy: date
    # asc | desc
    sortOrder: desc
    
toc:
  displayTags: true
    
highlight:
  copy:
    enable: true
    # hover | always
    display: always

comments:
  enable: false

analytics:
  umami:
    serverURL: "https://cloud.umami.is/script.js"
    websiteID: "741a89fe-ed67-43ff-b22a-fe3354b2ef8d"
    autoTrack: true
    doNotTrack: true
