version: 2
updates: 
  - package-ecosystem: github-actions 
    directory: /
    schedule:
      interval: weekly 
      day: thursday
  - package-ecosystem: gitsubmodule 
    directory: /
    schedule:
        interval: weekly 
        day: thursday
