version: 2
updates: 
  - package-ecosystem: github-actions
    directory: "/"
    labels:
      - dependencies
      - autosquash
    schedule:
      interval: "daily"
  - package-ecosystem: gitsubmodule
    schedule:
        interval: "daily"
    directory: / 
