baseURL = "https://shaharnaveh.github.io/"
languageCode = "en-us"
title = "snaveh"
theme = "PaperMod"


[params]
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true
    ShowReadingTime = true
    ShowToc = true
    TocOpen = true

[params.assets]
disableFingerprinting = true


[privacy]
  [privacy.disqus]
    disable = true

  [privacy.googleAnalytics]
    disable = true

  [privacy.instagram]
    disable = true

  [privacy.twitter]
    disable = true

  [privacy.vimeo]
    disable = true

  [privacy.youtube]
    disable = true
