name: Update git submodules
on:
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Update module
        run: |
          ls
          git submodule foreach 'git reset --hard && git checkout . && git clean -fdx'
          git submodule update --init --recursive --rebase --force
          #git submodule update --init --recursive --checkout -f --remote
          ls
          git config --global user.name "GitHub Action"
          git config --global user.email "noreply@github.com"
          git status
          git commit -am "Update git submodules"
          git push
